CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exercises (
    exercise_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    target_muscle VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE TABLE workouts (
    workout_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    workout_date DATE NOT NULL,
    notes TEXT,
    CONSTRAINT fk_workouts_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE workout_exercises (
    workout_exercise_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id INTEGER NOT NULL,
    exercise_id INTEGER NOT NULL,
    sets INTEGER NOT NULL
        CONSTRAINT ck_workout_exercises_sets_positive CHECK (sets > 0),
    reps INTEGER NOT NULL
        CONSTRAINT ck_workout_exercises_reps_positive CHECK (reps > 0),
    weight_kg NUMERIC(6, 2) NOT NULL
        CONSTRAINT ck_workout_exercises_weight_nonnegative
        CHECK (weight_kg >= 0),

    CONSTRAINT fk_workout_exercises_workout
        FOREIGN KEY (workout_id)
        REFERENCES workouts(workout_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_workout_exercises_exercise
        FOREIGN KEY (exercise_id)
        REFERENCES exercises(exercise_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT uq_workout_exercise_pair
        UNIQUE (workout_id, exercise_id)
);

INSERT INTO users (username, email)
VALUES ('demo_user', 'demo@fittracker.local');

    ),
    (
        'Overhead Press',
        'Shoulders',
        'Standing barbell shoulder press.'
    ),
    (
        'Triceps Pushdown',
        'Triceps',
        'Cable pushdown for the triceps.'
    );

INSERT INTO exercises (name, target_muscle, description)
VALUES
    (
        'Bench Press',
        'Chest',
        'Flat barbell press for chest strength.'
    ),
    (
        'Incline Dumbbell Press',
        'Chest',
        'Incline dumbbell press targeting the upper chest.'
    ),
    (
        'Push-Up',
        'Chest',
        'Bodyweight pressing exercise for the chest and triceps.'
    ),
    (
        'Squat',
        'Legs',
        'Barbell back squat for lower-body strength.'
    ),
    (
        'Leg Press',
        'Legs',
        'Machine-based pressing movement for the lower body.'
    ),
    (
        'Walking Lunge',
        'Legs',
        'Alternating lunge movement for leg strength and balance.'
    ),
    (
        'Deadlift',
        'Back',
        'Barbell pull for posterior-chain strength.'
    ),
    (
        'Romanian Deadlift',
        'Hamstrings',
        'Hip-hinge movement targeting the hamstrings and glutes.'
    ),
    (
        'Barbell Row',
        'Back',
        'Bent-over barbell pulling exercise for the upper back.'
    ),
    (
        'Lat Pulldown',
        'Back',
        'Cable pulling exercise targeting the latissimus muscles.'
    ),
    (
        'Overhead Press',
        'Shoulders',
        'Standing barbell shoulder press.'
    ),
    (
        'Lateral Raise',
        'Shoulders',
        'Dumbbell raise targeting the lateral shoulder muscles.'
    ),
    (
        'Biceps Curl',
        'Biceps',
        'Curling movement for isolated biceps training.'
    ),
    (
        'Triceps Pushdown',
        'Triceps',
        'Cable pushdown for the triceps.'
    ),
    (
        'Standing Calf Raise',
        'Calves',
        'Standing exercise for strengthening the calf muscles.'
    )
ON CONFLICT (name) DO NOTHING;
